[package]
name = "uuuddd4"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33"
rayon = "1.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1 
panic = "abort"
rayon = "1.8"